# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Version
        run: go version

      - name: Install claat
        run: |
          go install github.com/googlecodelabs/tools/claat@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Check claat binary
        run: ls -al $HOME/go/bin

      - name: Create codelab artifacts
        run: ./create-artifacts.sh

      - name: Verify artifacts directories
        run: |
            for dir in $(find . -type d -name '*-workshop'); do
              ls -al "$dir"
            done
      
      - name: Commit and push artifacts to gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b gh-pages
          ls -al
          for dir in $(find . -type d -name '*-workshop'); do
              git add "$dir"
          done
          git status
          git commit -m 'Add workshop codelab artifacts'
          git push

        
