# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Version
        run: go version

      - name: Install claat
        run: go install github.com/googlecodelabs/tools/claat@latest

      - name: Check claat binary
        run: ls -al $HOME/go/bin

      - name: Check file
        run: ls -al sample/codelab.md

      - name: Create codelab artifacts
        run: $HOME/go/bin/claat export sample/codelab.md
