# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Version
        run: go version

      - name: Install claat
        run: |
          go install github.com/googlecodelabs/tools/claat@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Check claat binary
        run: ls -al $HOME/go/bin

      - name: Create codelab artifacts
        run: ./create-artifacts.sh

      - name: Publish codelab artifacts
        uses: actions/upload-artifact@v4
        with:
          name: codelab-artifacts
          path: '**/*-artifacts/**'

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: '**/*-artifacts/**'
          publish_branch: gh-pages
        
